project_name: rmlast
builds:
  - binary: rmlast
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - solaris
      - windows
    goarch:
      - amd64
      - 386