name: CI
on:
  push:
  pull_request:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions/setup-go@v3
        with:
          go-version: 1.14
      
      - name: Format
        run: go fmt

      - name: Build
        run: go build -v